version: '3.9'
 
services:
  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
    environment:
      - NODE_ENV=development